### ISSUE TITLE
[FEATURE] Custumize training loop

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [GRAAL-Research/poutyne#104]
Hi there :)

What if I have to change the training loop, e.g. trian gans? 

Thank you!

Cheers,

Francesco

**Comment by freud14** [comment]
Hi Francesco, 

Thank you for your idea. We actually already had the same idea in our mind for a while. However, changing the training loops to support special training styles such as GANs' is not going to be trivial and is quite an undertaking. I think we would need to create another class replacing Model to implement that. Anyhow, I'm open to suggestions on how we could implement this. There are some components of the current code base that we could probably re-use but we still need to think how we want to implement that.

Anyway, if you would be willing to implement this, let me know and we can collaborate to get it done.

Thank you.

Frédérik

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @freud14, thank you for your reply! I have some ideas to improve poutyne while making it as flexible as pytorch-lighting (that I don't like it). But, IMHO, poutyne should be rewritten "from scratch".  Are you working on this project alone? Are you up for a call to discuss ideas? 

Cheers, 

Francesco

**Comment by freud14** [comment]
We are a few working on it. Yes, we can discuss. I will send you an e-mail in a few minutes about that.

**Comment by FrancescoSaverioZuppichini** [comment]
Sure, thank you mate
