### ISSUE TITLE
[BUG] Experiment test crashes when using multiple learning rates

### ISSUE THREAD

**Issue by gletarte** [GRAAL-Research/poutyne#108]
**Describe the bug**
When using the `Experiment` module with multiple learning rates, the `test` function crashes when it tries to load the metrics. This must occur because the learning rates are logged as a list ([0.001, 0.0001]) in the log.tsv instead of a single float value.

**To Reproduce**
Use an optimizer where different parameters have different learning rates to train a network using the `Experiment` module, and call the `test` function.
```
optimizer = torch.optim.SGD([{'params': model.word_embedding.parameters(), 'lr': 0.001}, 
                             {'params': model.classifier.parameters(), 'lr':0.01}])
```

**Expected behavior**
Calling the `test` function on experiment should not result in a crash.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 5.11.7

**Comment by freud14** [comment]
A temporary workaround would be to pass `verbose=False`.

**Comment by freud14** [comment]
Issue is fixed in dev and will be fixed in next release.
