### ISSUE TITLE
[FEATURE] Add `.pre-commit-config.yml`

### ISSUE THREAD

**Issue by SauravMaheshkar** [GRAAL-Research/poutyne#124]
I noticed that most of (if not all) the steps of the Contributing wiki can be automated via [**pre-commit**](https://pre-commit.com/). Having [**pre-commit**](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

I'd be more than happy to take this up.

**Comment by freud14** [comment]
Hi, thank you for the suggestion. It seems to me that it would add a bit of overhead to run all the tests et al. every time a commit is done. And I think most of the time you just want to do commits and make the CI pipeline pass at the end. However, running black and maybe pylint could be a good idea. What do you think?

**Comment by SauravMaheshkar** [comment]
Sure sounds good. Will open a PR in a while 😁.
