### ISSUE TITLE
Name of the library might be related to Russian oligarch

### ISSUE THREAD

**Issue by cprimex** [GRAAL-Research/poutyne#149]
Please change the name so it is not related to a warmongering Russian oligarch. It is offensive.

**Comment by cprimex** [comment]
I spoke with the author and this is fine

**Comment by gbmarc1** [comment]
For future non-Canadian people that wonder the same thing "Poutine" is a French Canadian dish.

https://en.wikipedia.org/wiki/Poutine

The package documentation explains why the authors named it as such.

https://poutyne.org/#why-this-name-poutyne
