### ISSUE TITLE
[BUG] _XLA_AVAILABLE error 

### ISSUE THREAD

**Issue by davebulaval** [GRAAL-Research/poutyne#169]
I've bumper my local Poutyne version, and I keep getting this error since torchmetrics is not updated at the same time. I guess better error handling (error verbosity) would be a nice improvement.

**Comment by davebulaval** [comment]
Fixed if torchmetrics is updated to latest.

**Comment by freud14** [comment]
Hey, can you me a code sample that triggers the error and the version of torchmetrics?

**Comment by davebulaval** [comment]
I don't have the exact version since I have bumped to the latest, but I guest actual latest minus 1 version.

Code was a classic training loop. It is really when you import `_XLA_AVAILABLE` from torchmetrics that does not include this variable that it fails.

A simple try, catch with a more verbose error handling would be sufficient IMO.

**Comment by freud14** [comment]
Fixed by d17f97dcaf95c0e67687fe8fa2f390f881e0e79f.
