### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by sudarshan85** [GRAAL-Research/poutyne#18]
I think it would be nice to have a progress bar indicating the status of training. There's tons of examples to implement this, but I think the one used by FastAI would be nice. [Here](https://github.com/fastai/fast_progress/tree/master/fast_progress) is the repo for it and [here](https://github.com/fastai/fast_progress/tree/master/fast_progress) is the actual python file that implements it. I'd be happy to submit a PR for it, if someone can point me in the right direction of where this would go.

**Comment by freud14** [comment]
Hi, the FastAI one seems to be especially for IPython Notebooks. As suggested in Issue #13, maybe it should be a callback that uses tqdm. Still, for IPython Notebooks, it could be interesting to have that. Either we integrate the fast_progress library into a callback or we code one directly in a callback.

**Comment by davebulaval** [comment]
- fastprogress
- tqdm

**Comment by davebulaval** [comment]
Note: _flag verbose for progresscallback (none, epoch, epoch and step), progresscallback only for every n epochs_

**Comment by davebulaval** [comment]
Overhead:
fastprogress: unknow
tqdm: 60 ns
ProgressBar: 800 ns
