### ISSUE TITLE
Suggestions for a new name

### ISSUE THREAD

**Issue by freud14** [GRAAL-Research/poutyne#22]
Hello everyone,
Due to some connotation of the name Pytoune (pitoune) in Quebec French, we have decided to change the name of the library. We are thus seeking suggestions from our community for a new name. Here are some of our current suggestions:

* TorchLighter
* (py)scorch
* torchflow
* bonfire
* bonpyre
* flambeau
* chalumeau
* briquet
* Krass
* CakeTorch
* BreezeTorch
* pyromaniac
* PyTern (Python + Lantern)
* PyTwinkle
* Poutyne

Right now, the suggestions are all related to fire/torch but they don't have to. The new name can be really anything; it just has to sound nice. Of course, it'd be nice if it is somewhat related to what the library does. Also, it could be a name in another language such as the French names suggested above.

Some of the suggestions above are already names for other things but nothing really major or related. We have to take care of choosing a name that is not already the name of something else.

So, if you any suggestions or comments on the already suggested names, please post below! 

Thank you.

Frédérik

**Comment by K-miy** [comment]
bougie
    lampion (Lampyon)
    oupille (Oupy) http://cnrtl.fr/definition/dmf/oupille

Thanks to synonyms dictionary ;)

**Comment by DbrRoxane** [comment]
Lampion/Lampyon, I like it!!!

**Comment by jonathangingras** [comment]
Holzfeuer (wood/log fire) (related to your pitounes)

**Comment by freud14** [comment]
The name is now changed for Poutyne.
