### ISSUE TITLE
Make logo and README to the project

### ISSUE THREAD

**Issue by freud14** [GRAAL-Research/poutyne#3]
<strike>The logo should be inspired from pytorch's Logo and have a log (like a wood log y'know) in fire.</strike> The description of the project in the README should start with something like "Pytoune is a Keras-like interface for the PyTorch framework...." and should have SEO (search engine optimization) in mind. I don't know what it is possible for that in github/markdown. We should also includes lots of examples of what's possible with our framework.

**Comment by freud14** [comment]
Just missing the logo.

**Comment by sudarshan85** [comment]
![logo-1](https://user-images.githubusercontent.com/488428/44065989-035889e6-9f3c-11e8-8e98-17ccd52bc261.png)

First Attempt. Let me know what you think.

**Comment by freud14** [comment]
Hi. Thank your for your idea. We actually had one in preparation but yours looks nice. We'll probably post the one we had here and maybe we could merge them or improve one of them using inspiration from the other. What do you think?

**Comment by sudarshan85** [comment]
Sounds great. Let me know how I can help.

**Comment by jsleb333** [comment]
Hi, here's the logo that was in progress. What do you think?

![logo_pytoune](https://user-images.githubusercontent.com/11812338/44360308-7cbbf380-a488-11e8-8714-f1c869e7128b.png)

**Comment by sudarshan85** [comment]
It looks nice! Couple of things:

- The font is a bit distorted and I couldn't read of "Pytoune" immediately.
- I think we could have more color?

**Comment by sudarshan85** [comment]
- Currently, the end of the log is an ellipse.  Would it make sense to make it a circle? That way, it would be smaller and we can play with the font to make it less curved. We are currently looking at an enhanced picture but I think we need to keep in mind that this is a logo (which would be small and corner of a website). So, I think its important that "Pytoune" stands out for easier reading. In other words, the top of the leaf, and the letter "P" could be at the same level.

- I'm guess that the leaf at the end is supposed to represent fire? If that is the case, I would make it more golden/red. Again, I would like to the software name to lookout. So I would make the logs more transparent (give it a lighter shade) and choose a more vibrant color for the word.

Let me know what you think.

**Comment by jsleb333** [comment]
I'm not sure I understand what you mean. The concept of my logo was to have an angle view of a log, with the name "Pytoune" in the shape of the body and the descender of the "y" being a branch. Your suggestion seems to forego this idea. On the other hand, if you didn't see that at first glance, maybe we should explore a different avenue.

The leaf was not intended to be a flame. I get your point with more vibrant colors, however it is hard to choose vibrant colors that would still look like a wood log. But I'll keep your points in mind.

**Comment by sudarshan85** [comment]
> I'm not sure I understand what you mean. The concept of my logo was to have an angle view of a log, with the name "Pytoune" in the shape of the body and the descender of the "y" being a branch

Oh OK! That makes far more sense. I didn't look at it in that way. But yes..that is clever :)

> The leaf was not intended to be a flame.
I thought the logo needed to have log in fire according to OP?

**Comment by jsleb333** [comment]
> I thought the logo needed to have log in fire according to OP?

Yes it is indeed written, but I took some liberties in my creative spirit. Moreover, I work with @freud14 and he said that it was more of a guide than an absolute criterion.

**Comment by freud14** [comment]
Since we changed the name of the library, the logo concepts that have been developed until now are not suitable anynore :( sorry.

**Comment by davebulaval** [comment]
@freud14 we should try another call for logo for the new name.

**Comment by freud14** [comment]
PR #47 has just been accepted. It contains a new logo very similar to what @sudarshan85 proposed.
