### ISSUE TITLE
Possible bug with steps_per_epoch

### ISSUE THREAD

**Issue by prabhuteja12** [GRAAL-Research/poutyne#32]
Hi, 
I'm using the steps_per_epoch argument of the Model's fit_generator function and the functionality I observe doesn't seem to be correct. 

> steps_per_epoch (int, optional): Number of batch used during one
                epoch. Obviously, using this argument may cause one epoch not to
                see the entire training dataset or see it multiple times.
                (Defaults the number of steps needed to see the entire
                training dataset)

Is my understanding correct that if we use the standard MNIST train-test split, I set the n_epochs= 1 and steps_per_epoch to 120000, it is the equivalent of training 2 epochs. However, it doesn't seem to work when the size of the dataset object is less than the steps_per_epoch. The following code reproduces the scenario. This has been taken from the mnist example provided. 

```
import math
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data.dataset import Subset

from torchvision import transforms
from torchvision.datasets.mnist import MNIST

from poutyne.framework import Model, ModelCheckpoint, CSVLogger
from poutyne import torch_to_numpy
from poutyne.layers import Flatten


torch.manual_seed(42)
np.random.seed(42)

cuda_device = 0
device = torch.device("cuda:%d" %
                      cuda_device if torch.cuda.is_available() else "cpu")
train_split_percent = 0.8
batch_size = 32
learning_rate = 0.01
n_epoch = 5
num_classes = 10


train_dataset = MNIST('./mnist/', train=True, download=True,
                      transform=transforms.ToTensor())
valid_dataset = MNIST('./mnist/', train=True, download=True,
                      transform=transforms.ToTensor())
test_dataset = MNIST('./mnist/', train=False, download=True,
                     transform=transforms.ToTensor())
num_data = len(train_dataset)
indices = list(range(num_data))
np.random.shuffle(indices)

split = math.floor(train_split_percent * num_data)

train_indices = indices[:split]
train_dataset = Subset(train_dataset, train_indices)

valid_indices = indices[split:]
valid_dataset = Subset(valid_dataset, valid_indices)

train_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=batch_size, shuffle=True)
valid_loader = torch.utils.data.DataLoader(
    valid_dataset, batch_size=batch_size)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size)


def train(name, pytorch_module):
    # Finally, we start the training and output its final test
    # loss and accuracy.

    # Optimizer and loss function
    optimizer = optim.SGD(pytorch_module.parameters(),
                          lr=learning_rate, weight_decay=0.001)
    loss_function = nn.CrossEntropyLoss()

    # Poutyne Model
    model = Model(pytorch_module, optimizer,
                  loss_function, metrics=['accuracy'])

    # Send model on GPU
    model.to(device)

    # Train
    model.fit_generator(train_loader, valid_loader,
                        epochs=1, steps_per_epoch=120000)

    # Test
    test_loss, test_acc = model.evaluate_generator(test_loader)
    print('Test:\n\tLoss: {}\n\tAccuracy: {}'.format(test_loss, test_acc))


def create_convolutional_network():
    return nn.Sequential(
        nn.Conv2d(1, 32, 3, padding=1),
        nn.ReLU(),
        nn.Conv2d(32, 64, 3, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),
        nn.Dropout(0.25),
        Flatten(),
        nn.Linear(64*14*14, 128),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(128, num_classes)
    )


conv_net = create_convolutional_network()
print(conv_net)

# Start training
train('conv', conv_net)
```

In this the train generator has 48000 samples. When I set the steps_per_epoch=120000 and batch_size=32 (as above), the number of batches/steps should be `120000/32 = 3750`. However, the code stops after `48000/32=1500` batches/steps. 

This behavior in the code seems to be stemming from [https://github.com/GRAAL-Research/poutyne/blob/master/poutyne/framework/iterators.py#L17](here). Specifically,
`zip(range(steps), generator)` is truncated to the shorter of sequences. Simple example:
```
for x, y in zip(range(3), range(5)):
    print(x, y)
```
prints
```
0 0
1 1
2 2
```
So if the len(generator) < num_steps, then the zip only iterates over the generator once, and not multiple times (as the documentation states). 

Is this expected behavior?

**Comment by freud14** [comment]
Hi,
The "see it multiple times" part of the docs is because if you pass an infinite generator, then you can loop through it multiple times. I agree that it might be considered as a bug when the generator is not infinite. So, either we change the doc or we fix the bug by transforming the generator into an infinite generator.

Thank you.

Frédérik

**Comment by prabhuteja12** [comment]
> So, either we change the doc or we fix the bug by transforming the generator into an infinite generator.
I would say the DataLoader is made into an infinite generator. That makes more sense than constraining `steps_per_epoch <= len(DataLoader)`. 

Would this suffice?
```
def cycle(iterable):  # Equivalent to itertools cycle, without any extra memory requirement
    while True:
        for x in iterable:
            yield x

```

**Comment by freud14** [comment]
Yes, something like that could work (to be tested):

```python
def cycle(iterable):  # Equivalent to itertools cycle, without any extra memory requirement
    while True:
        for x in iterable:
            yield x

def _get_step_iterator(steps, generator):
    count_iterator = range(1, steps + 1) if steps is not None else itertools.count(1)
    generator = cycle(generator) if steps is not None else generator
    return zip(count_iterator, generator)
```

**Comment by prabhuteja12** [comment]
Cool! Would you be able to fix it on master?

**Comment by freud14** [comment]
It's pushed on master. I did not do additional test. Can you verify that it works for you?

**Comment by prabhuteja12** [comment]
Just tested this out on the same examples and it works great! Thanks for the quick turnaround!! I'll close this issue now.
