### ISSUE TITLE
How to adjust the learning rate when fiting？

### ISSUE THREAD

**Issue by yangj257** [GRAAL-Research/poutyne#33]
Hi,
First of all，thank you for providing such a wonderful tool. 

the issue is as follows，I'm using MultiStepLR:

from poutyne.framework.callbacks.lr_scheduler import MultiStepLR
optimizer = torch.optim.Adam(resnet.parameters(),lr=0.01)
model = Model(resnet, optimizer, criterion, metrics=['accuracy'])
scheduler = MultiStepLR(optimizer, milestones=[18,36,70], gamma = 0.1)

history=model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=epochs,
    batch_size=128,
    verbose=True,
    callbacks=[scheduler]
  )
the error message is “TypeError: __init__() got multiple values for argument 'milestones”

What should I do next?

Could you please provide more and more detailed documentation?For instance, how to use the available callbacks. It allows beginners to get started quickly and make your project get more attention.Thank you very much!

**Comment by freud14** [comment]
Hi, you don't need to pass the optimizer. If you remove it from the arguments, it should work.

**Comment by yangj257** [comment]
it works！thanks！
