### ISSUE TITLE
UnicodeDecodeError during installation

### ISSUE THREAD

**Issue by siyideng** [GRAAL-Research/poutyne#40]
**Describe the bug**
Installation error. 

**To Reproduce**
`pip3 install -U poutyne`
or
`pip3 install -U git+https://github.com/GRAAL-Research/poutyne.git`

**Desktop (please complete the following information):**
OS: Ubuntu 18.4

**Screenshots**

> Collecting git+https://github.com/GRAAL-Research/poutyne.git
>   Cloning https://github.com/GRAAL-Research/poutyne.git to /tmp/pip-oo9s7g9u-build
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-oo9s7g9u-build/setup.py", line 8, in <module>
>         readme = f.read()
>       File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4320: ordinal not in range(128)

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-oo9s7g9u-build/

**Comment by freud14** [comment]
I guess if your locals are not utf-8, then you have an encoding error. Fixed by #41.
