### ISSUE TITLE
[FEATURE] Unit-test Experiment class

### ISSUE THREAD

**Issue by TortillasAlfred** [GRAAL-Research/poutyne#49]
**Is your feature request related to a problem? Please describe.**
The Experiment class code is currently untested. We will have to introduce unit tests for it.

**Describe the solution you'd like**
Unit-testing this class does not appear particularly straightforward to me. For example, have a look at the load_checkpoint method: if we wish to test that the correct loading method is used acording to the checkpoint arg, we will only end up reproducing the method's code in the tests and end up testing Python instead of our model's logic. Also, since the callbacks and model are all tested on their own and Experiment is mainly a Model + Callbacks wrapper, what is really the Experiment-only logic we wish to test ?

I am open to writing the tests to the class, but would enjoy some inputs regarding the tests' orientation.

**Comment by freud14** [comment]
Mostly done in 24a02a021ce3b706687b7477d47ea52e4b72ab24.
