### ISSUE TITLE
[BUG] val_accuracy as a monitor metric for Experiment class

### ISSUE THREAD

**Issue by Dpothier** [GRAAL-Research/poutyne#69]
**Describe the bug**
The Experiment class does not recognize "val_accuracy" as a valid value for monitor_metric, while the doc implies that both acc and accuracy should be supported.

**To Reproduce**
Instantiate an Experiment, passing "val_accuracy" as value for the monitor_metric parameter

**Expected behavior**
The Experiment should accept the value and track validation accuracy to determine the best model, as it does when the value "val_acc" is passed.

**Comment by freud14** [comment]
The monitor metric has to be a key in the log dictionnary passed to callbacks. Maybe we should specify that in the doc?

**Comment by freud14** [comment]
Hi, since version 1.0, I updated the documentation about metrics. Let me know if you think there are some things not clear. I will close this issue.
