### ISSUE TITLE
[BUG] Reset EpochMetric is assumed to be handled, which shouldn't

### ISSUE THREAD

**Issue by ngarneau** [GRAAL-Research/poutyne#72]
**Describe the bug**
EpochMetrics are designed to accumulate statistics for a given Epoch.
Given their interface, there is a method to accumulate and a method to retrieve the said metric.
If one does not explicitly reset the accumulators within the `get_metric` method, statistics are wrong.

**To Reproduce**
```
class CorrelationMetric(EpochMetric):
    def __init__(self) -> None:
        super().__init__()
        self.scores = list()
        self.distances = list()

    def forward(self, x, y):
        # Accumulate metrics here
        e3 = x['e3']
        scores = x['scores']
        distances = x['distances']
        for i, (s, d) in enumerate(zip(scores, distances)):
            self.scores.append(1 - float(s[e3[i]]))
            self.distances.append(float(d))  # We append the distance

    def get_metric(self):
        val =  np.corrcoef(self.scores, self.distances)[0][1]
        self.reset()  # Forgetting this line is problematic, and people will do!
        return val

    def reset(self) -> None:
        self.scores = list()
        self.distances = list()
```

**Expected behavior**
The interface should force to implement the `reset` method, and IMO the training loop should call it after the end of an epoch, not the `get_metric` method.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.20

**Comment by freud14** [comment]
I made PR #73 if we want to go with this option. However, this is a small breaking change. @davebulaval What do you think?

**Comment by davebulaval** [comment]
I think @ngarneau is right, it was not explicit that reset should be present in `get_metric` and it is more clear to call it as suggested.
